name: fintek
description: A flutter assignment from Chinmay Phadke of Cambridge Wealth

publish_to: 'none'

version: 1.0.5+6

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sizer:
  flutter_bloc:
  equatable:
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/